// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKflCrMerPHz99HDS78lHMCgno4GnErJA',
    appId: '1:287768105432:web:c5367cbc5d6ffe8ead62ad',
    messagingSenderId: '287768105432',
    projectId: 'tpfinal-mobil',
    authDomain: 'tpfinal-mobil.firebaseapp.com',
    storageBucket: 'tpfinal-mobil.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkJwwEHE5GydIXZYL248MOirqVsflOYPo',
    appId: '1:287768105432:android:7ef54e1b577f41bfad62ad',
    messagingSenderId: '287768105432',
    projectId: 'tpfinal-mobil',
    storageBucket: 'tpfinal-mobil.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxFkN6LRDF0sMnN2PTdSeHyU8Jq7e3yl8',
    appId: '1:287768105432:ios:510fbb2327112510ad62ad',
    messagingSenderId: '287768105432',
    projectId: 'tpfinal-mobil',
    storageBucket: 'tpfinal-mobil.appspot.com',
    iosClientId: '287768105432-m28m7a0lehlok6e0pm1n35u0tvmdod0j.apps.googleusercontent.com',
    iosBundleId: 'com.example.tpfinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxFkN6LRDF0sMnN2PTdSeHyU8Jq7e3yl8',
    appId: '1:287768105432:ios:510fbb2327112510ad62ad',
    messagingSenderId: '287768105432',
    projectId: 'tpfinal-mobil',
    storageBucket: 'tpfinal-mobil.appspot.com',
    iosClientId: '287768105432-m28m7a0lehlok6e0pm1n35u0tvmdod0j.apps.googleusercontent.com',
    iosBundleId: 'com.example.tpfinal',
  );
}
